name: Build Windows

on:
  release:
    types: [published]

jobs:
  build:
    steps:
      - name: Install Dependencies
        run: npm ci

      - name: Build and Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run build
          npx electron-builder --windows --publish always
